version: '3'

services:
  application_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: alt_school_user
      POSTGRES_PASSWORD: secretPassw0rd
      POSTGRES_DB: ecommerce
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data_19:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_setup/init.sql:/docker-entrypoint-initdb.d/init.sql